# Module constants

LIMIT = 20
NUM_OF_THINGS = [4, 10, 15, 20, 22, 25, 27, 30, 32, 35, 37, 40]

NR_INST_FILE_PATH_PREFIX = "NR/NR"
ZR_INST_FILE_PATH_PREFIX = "ZR/ZR"
INST_FILE_PATH_POSTFIX = "_inst.dat"

NR_SOL_FILE_PATH_PREFIX = "NR/NK"
ZR_SOL_FILE_PATH_PREFIX = "ZR/ZK"
SOL_FILE_PATH_POSTFIX = "_sol.dat"

BF = "BRUTE FORCE"
BF_BETTER = "BETTER BRUTE FORCE"
BB = "BRANCH & BOUND"

ALL_INSTANCES = "completely"
RANDOM_INSTANCE = "partially"
